LANG_DICT_NOT_FOUND_ERROR = "Dictionary not found for the language : {}"
WEBPAGE_NOT_FOUND_ERROR = "The requested webpage was not found for the url : {}"
CRAWLING_VOCABULARY_NOT_FOUND = "No vocabulary list found in the webpage"
URL_FORMAT_NOT_VALID = "The format of the URL is not valid : {}"
CATEGORY_NOT_FOUND = "No category found in the webpage"
MONGO_DATA_NOT_FOUND = "No data found in the MongoDB for the given parameters"
S3_DATA_NOT_FOUND = "No data found in the S3 bucket for the given parameters"
