# This file contains the status constants for the words related to a vocabulary list
# in order to keep track of the process of the words.

STATUS_WAITING_SCRAP = "WAITING FOR SCRAPING"
STATUS_WAITING_PROCESSING = "WAITING FOR PROCESSING"
STATUS_WAITING_AI_PROCESSING = "WAITING FOR AI PROCESSING"
STATUS_FINISHED = "FINISHED"

STATUS_ERROR_SCRAP = "ERROR WHILE SCRAPING"
STATUS_ERROR_PROCESSING = "ERROR WHILE PROCESSING"
STATUS_ERROR_AI_PROCESSING = "ERROR WHILE AI PROCESSING"
